package TaskManager;

/**
* TaskManager/TaskStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:24:01 PM WET
*/

public final class TaskStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public TaskManager.TaskStatus value = null;

  public TaskStatusHolder ()
  {
  }

  public TaskStatusHolder (TaskManager.TaskStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TaskManager.TaskStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TaskManager.TaskStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TaskManager.TaskStatusHelper.type ();
  }

}
