package TaskManager;


/**
* TaskManager/TaskHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:24:01 PM WET
*/

abstract public class TaskHelper
{
  private static String  _id = "IDL:TaskManager/Task:1.0";

  public static void insert (org.omg.CORBA.Any a, TaskManager.Task that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TaskManager.Task extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "title",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "description",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "dueDate",
            _tcOf_members0,
            null);
          _tcOf_members0 = TaskManager.TaskStatusHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "status",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "assignedTo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (TaskManager.TaskHelper.id (), "Task", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TaskManager.Task read (org.omg.CORBA.portable.InputStream istream)
  {
    TaskManager.Task value = new TaskManager.Task ();
    value.id = istream.read_string ();
    value.title = istream.read_string ();
    value.description = istream.read_string ();
    value.dueDate = istream.read_string ();
    value.status = TaskManager.TaskStatusHelper.read (istream);
    value.assignedTo = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TaskManager.Task value)
  {
    ostream.write_string (value.id);
    ostream.write_string (value.title);
    ostream.write_string (value.description);
    ostream.write_string (value.dueDate);
    TaskManager.TaskStatusHelper.write (ostream, value.status);
    ostream.write_string (value.assignedTo);
  }

}
