package TaskManager;


/**
* TaskManager/TaskService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:24:01 PM WET
*/

public interface TaskService extends TaskServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TaskService
