package TaskManager;


/**
* TaskManager/TaskListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:24:01 PM WET
*/

public final class TaskListHolder implements org.omg.CORBA.portable.Streamable
{
  public TaskManager.Task value[] = null;

  public TaskListHolder ()
  {
  }

  public TaskListHolder (TaskManager.Task[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TaskManager.TaskListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TaskManager.TaskListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TaskManager.TaskListHelper.type ();
  }

}
