package TaskManager;


/**
* TaskManager/Task.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:24:01 PM WET
*/

public final class Task implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String title = null;
  public String description = null;
  public String dueDate = null;
  public TaskManager.TaskStatus status = null;
  public String assignedTo = null;

  public Task ()
  {
  } // ctor

  public Task (String _id, String _title, String _description, String _dueDate, TaskManager.TaskStatus _status, String _assignedTo)
  {
    id = _id;
    title = _title;
    description = _description;
    dueDate = _dueDate;
    status = _status;
    assignedTo = _assignedTo;
  } // ctor

} // class Task
