package TaskManager;

/**
* TaskManager/TaskServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:24:01 PM WET
*/

public final class TaskServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public TaskManager.TaskService value = null;

  public TaskServiceHolder ()
  {
  }

  public TaskServiceHolder (TaskManager.TaskService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TaskManager.TaskServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TaskManager.TaskServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TaskManager.TaskServiceHelper.type ();
  }

}
