package TaskManager;


/**
* TaskManager/TaskStatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:23:31 PM WET
*/

abstract public class TaskStatusHelper
{
  private static String  _id = "IDL:TaskManager/TaskStatus:1.0";

  public static void insert (org.omg.CORBA.Any a, TaskManager.TaskStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TaskManager.TaskStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (TaskManager.TaskStatusHelper.id (), "TaskStatus", new String[] { "NOT_STARTED", "IN_PROGRESS", "COMPLETED"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TaskManager.TaskStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    return TaskManager.TaskStatus.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TaskManager.TaskStatus value)
  {
    ostream.write_long (value.value ());
  }

}
