package TaskManager;


/**
* TaskManager/TaskServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:23:31 PM WET
*/

public abstract class TaskServicePOA extends org.omg.PortableServer.Servant
 implements TaskManager.TaskServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addTask", new java.lang.Integer (0));
    _methods.put ("removeTask", new java.lang.Integer (1));
    _methods.put ("getTasks", new java.lang.Integer (2));
    _methods.put ("updateTaskStatus", new java.lang.Integer (3));
    _methods.put ("assignTask", new java.lang.Integer (4));
    _methods.put ("updateTask", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TaskManager/TaskService/addTask
       {
         TaskManager.Task task = TaskManager.TaskHelper.read (in);
         this.addTask (task);
         out = $rh.createReply();
         break;
       }

       case 1:  // TaskManager/TaskService/removeTask
       {
         String id = in.read_string ();
         this.removeTask (id);
         out = $rh.createReply();
         break;
       }

       case 2:  // TaskManager/TaskService/getTasks
       {
         TaskManager.Task $result[] = null;
         $result = this.getTasks ();
         out = $rh.createReply();
         TaskManager.TaskListHelper.write (out, $result);
         break;
       }

       case 3:  // TaskManager/TaskService/updateTaskStatus
       {
         String id = in.read_string ();
         TaskManager.TaskStatus status = TaskManager.TaskStatusHelper.read (in);
         this.updateTaskStatus (id, status);
         out = $rh.createReply();
         break;
       }

       case 4:  // TaskManager/TaskService/assignTask
       {
         String id = in.read_string ();
         String user = in.read_string ();
         this.assignTask (id, user);
         out = $rh.createReply();
         break;
       }

       case 5:  // TaskManager/TaskService/updateTask
       {
         TaskManager.Task task = TaskManager.TaskHelper.read (in);
         this.updateTask (task);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TaskManager/TaskService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TaskService _this() 
  {
    return TaskServiceHelper.narrow(
    super._this_object());
  }

  public TaskService _this(org.omg.CORBA.ORB orb) 
  {
    return TaskServiceHelper.narrow(
    super._this_object(orb));
  }


} // class TaskServicePOA
