package TaskManager;


/**
* TaskManager/TaskServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:23:31 PM WET
*/

public interface TaskServiceOperations 
{
  void addTask (TaskManager.Task task);
  void removeTask (String id);
  TaskManager.Task[] getTasks ();
  void updateTaskStatus (String id, TaskManager.TaskStatus status);
  void assignTask (String id, String user);
  void updateTask (TaskManager.Task task);
} // interface TaskServiceOperations
