package TaskManager;


/**
* TaskManager/TaskServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:23:31 PM WET
*/

abstract public class TaskServiceHelper
{
  private static String  _id = "IDL:TaskManager/TaskService:1.0";

  public static void insert (org.omg.CORBA.Any a, TaskManager.TaskService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TaskManager.TaskService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TaskManager.TaskServiceHelper.id (), "TaskService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TaskManager.TaskService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TaskServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TaskManager.TaskService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TaskManager.TaskService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TaskManager.TaskService)
      return (TaskManager.TaskService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TaskManager._TaskServiceStub stub = new TaskManager._TaskServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TaskManager.TaskService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TaskManager.TaskService)
      return (TaskManager.TaskService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TaskManager._TaskServiceStub stub = new TaskManager._TaskServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
