package TaskManager;


/**
* TaskManager/TaskStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskManager.idl
* Friday, January 31, 2025 10:23:31 PM WET
*/

public class TaskStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static TaskManager.TaskStatus[] __array = new TaskManager.TaskStatus [__size];

  public static final int _NOT_STARTED = 0;
  public static final TaskManager.TaskStatus NOT_STARTED = new TaskManager.TaskStatus(_NOT_STARTED);
  public static final int _IN_PROGRESS = 1;
  public static final TaskManager.TaskStatus IN_PROGRESS = new TaskManager.TaskStatus(_IN_PROGRESS);
  public static final int _COMPLETED = 2;
  public static final TaskManager.TaskStatus COMPLETED = new TaskManager.TaskStatus(_COMPLETED);

  public int value ()
  {
    return __value;
  }

  public static TaskManager.TaskStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TaskStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TaskStatus
